name: CI Build

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        #run: npm install

      - name: Build AppImage (no publish)
        run: npx electron-builder --linux AppImage --publish never

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v7
        with:
          name: ytmd-appimage
          path: dist/*.AppImage
          if-no-files-found: error
          retention-days: 7